import type { Drill } from "../../types/practice";

/**
 * The drill library. Every drill carries a trackable metric and a success
 * threshold so a session produces a number, not just a tick.
 *
 * `success_threshold` and every recorded `score` are normalised 0-1 so the
 * progress engine can compare a contact ratio with a proximity average.
 */
export const DRILLS: Drill[] = [
  // ---------------------------------------------------------------- contact
  {
    id: "drill_9_ball_contact",
    name: "9-Ball Contact Drill",
    category: "contact",
    sub_category: "mid irons",
    description:
      "Three sets of nine balls with foot spray or impact tape on the face. Only centre strikes count.",
    instructions: [
      "Spray the face of a 7 iron with foot powder.",
      "Hit nine balls at a single target at 75% effort.",
      "Mark each strike: centre, toe, heel, thin, fat.",
      "Wipe and repeat for three sets of nine.",
    ],
    skill_trained: "centered_contact",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 27,
    equipment_required: ["foot spray or impact tape", "mid iron"],
    clubs: ["6_iron", "7_iron", "8_iron"],
    metric_to_track: "Solid-contact rate",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.75,
    progression_level: "drill_towel_gate_contact",
    regression_level: "drill_half_swing_contact",
  },
  {
    id: "drill_half_swing_contact",
    name: "Half-Swing Strike Ladder",
    category: "contact",
    sub_category: "technical",
    description:
      "Waist-to-waist swings building strike quality before adding speed. The regression drill for contact.",
    instructions: [
      "Set up with a 9 iron and a narrow stance.",
      "Swing waist to waist, holding the finish for one second.",
      "Count a rep as good only if the divot starts at or past the ball.",
      "Add a club length of swing every ten good reps.",
    ],
    skill_trained: "centered_contact",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 30,
    equipment_required: ["short iron"],
    clubs: ["9_iron", "pw"],
    metric_to_track: "Ball-first strikes",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: "drill_9_ball_contact",
    regression_level: null,
  },
  {
    id: "drill_towel_gate_contact",
    name: "Towel Gate Strike Test",
    category: "contact",
    sub_category: "mid irons",
    description: "A towel two inches behind the ball punishes any early low point.",
    instructions: [
      "Lay a folded towel two inches behind the ball.",
      "Hit twenty shots with a 7 iron at full speed.",
      "Any contact with the towel is a failed rep.",
    ],
    skill_trained: "centered_contact",
    difficulty: "advanced",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["towel", "mid iron"],
    clubs: ["6_iron", "7_iron"],
    metric_to_track: "Clean strikes",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.8,
    progression_level: null,
    regression_level: "drill_9_ball_contact",
  },
  {
    id: "drill_strike_zone_wedge",
    name: "Wedge Strike Zone",
    category: "wedges",
    sub_category: "contact",
    description: "Low-point control with wedges off a tight lie.",
    instructions: [
      "Draw a line on the turf or use a chalk line on a mat.",
      "Hit twenty wedge shots, aiming to start the divot on the target side of the line.",
      "Alternate between 50 and 80 yard swings.",
    ],
    skill_trained: "strike_quality",
    difficulty: "intermediate",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["chalk or line", "wedges"],
    clubs: ["gw", "sw", "lw"],
    metric_to_track: "Divot after the line",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.75,
    progression_level: null,
    regression_level: "drill_half_swing_contact",
  },

  // ----------------------------------------------------------- face control
  {
    id: "drill_gate_face_control",
    name: "Start Line Gate",
    category: "face_control",
    sub_category: "full swing",
    description:
      "Two alignment sticks six feet ahead form a gate. Only the face controls start line at impact.",
    instructions: [
      "Place two sticks six feet ahead, one yard apart, on your target line.",
      "Hit twenty 7 irons through the gate.",
      "Narrow the gate by six inches once you clear eighteen of twenty.",
    ],
    skill_trained: "start_line",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 20,
    equipment_required: ["2 alignment sticks"],
    clubs: ["7_iron", "8_iron"],
    metric_to_track: "Shots through the gate",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: "drill_shape_window",
    regression_level: "drill_split_hand_face",
  },
  {
    id: "drill_split_hand_face",
    name: "Split-Hand Face Awareness",
    category: "face_control",
    sub_category: "technical",
    description: "Splitting the hands exaggerates face rotation so you feel what the face is doing.",
    instructions: [
      "Grip a 9 iron with the hands four inches apart.",
      "Make slow half swings feeling the lead wrist control the face.",
      "Every fifth rep, return to a normal grip and hit a ball.",
    ],
    skill_trained: "face_control",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 25,
    equipment_required: ["short iron"],
    clubs: ["9_iron", "pw"],
    metric_to_track: "Shots starting within the window",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_gate_face_control",
    regression_level: null,
  },
  {
    id: "drill_shape_window",
    name: "Two-Window Shot Shaping",
    category: "face_control",
    sub_category: "shot shaping",
    description: "Alternate a deliberate draw and fade into two separate windows.",
    instructions: [
      "Pick two targets fifteen yards apart.",
      "Hit a draw to the right target, then a fade to the left target.",
      "A rep counts only if the ball both starts and curves as planned.",
    ],
    skill_trained: "shot_shaping",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 20,
    equipment_required: ["mid iron"],
    clubs: ["6_iron", "7_iron"],
    metric_to_track: "Shapes executed",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_gate_face_control",
  },

  // ------------------------------------------------------------- transition
  {
    id: "drill_pause_at_top",
    name: "Pause-at-the-Top Transition",
    category: "transition",
    sub_category: "sequencing",
    description:
      "A full stop at the top removes any rush from the change of direction and forces a ground-up start.",
    instructions: [
      "Swing to the top and pause for a full count of one.",
      "Start down by shifting pressure into the lead foot before the arms move.",
      "Hit ten paused reps, then five normal-tempo shots keeping the same feel.",
    ],
    skill_trained: "sequencing",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["mid iron"],
    clubs: ["6_iron", "7_iron", "8_iron"],
    metric_to_track: "Reps with correct sequence and centre strike",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: "drill_step_change_direction",
    regression_level: "drill_pump_transition",
  },
  {
    id: "drill_pump_transition",
    name: "Pump Drill",
    category: "transition",
    sub_category: "technical",
    description: "Two pumps into the delivery position before releasing the third swing.",
    instructions: [
      "Swing to the top, pump down to hip height twice.",
      "On the third, hit the shot.",
      "Feel the trail elbow lead the hands into delivery.",
    ],
    skill_trained: "sequencing",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 20,
    equipment_required: ["mid iron"],
    clubs: ["7_iron"],
    metric_to_track: "Clean strikes on the third swing",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_pause_at_top",
    regression_level: null,
  },
  {
    id: "drill_step_change_direction",
    name: "Step-Through Change of Direction",
    category: "transition",
    sub_category: "sequencing",
    description: "A trail-foot step during the downswing makes an out-of-sequence move impossible to hide.",
    instructions: [
      "Start with feet together.",
      "As the club reaches the top, step the lead foot out and swing.",
      "Any loss of balance is a failed rep.",
    ],
    skill_trained: "sequencing",
    difficulty: "advanced",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["mid iron"],
    clubs: ["7_iron", "8_iron"],
    metric_to_track: "Balanced reps with centre contact",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: null,
    regression_level: "drill_pause_at_top",
  },

  // ------------------------------------------------------------------ tempo
  {
    id: "drill_three_to_one_tempo",
    name: "3:1 Tempo Count",
    category: "tempo",
    sub_category: "rhythm",
    description: "Counting a three-to-one backswing-to-downswing ratio out loud.",
    instructions: [
      "Count one-two-three back, one down.",
      "Hit fifteen shots keeping the count identical regardless of club.",
      "Alternate a wedge and a mid iron every five shots.",
    ],
    skill_trained: "tempo",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 15,
    equipment_required: [],
    clubs: ["pw", "7_iron"],
    metric_to_track: "Reps on tempo",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.75,
    progression_level: "drill_eyes_closed_tempo",
    regression_level: null,
  },
  {
    id: "drill_eyes_closed_tempo",
    name: "Eyes-Closed Balance Finish",
    category: "tempo",
    sub_category: "balance",
    description: "Swinging with eyes closed exposes any tempo or balance problem immediately.",
    instructions: [
      "Set up, take one look at the target, then close your eyes.",
      "Swing and hold the finish for three seconds.",
      "Open your eyes before looking at the result and rate the balance.",
    ],
    skill_trained: "tempo",
    difficulty: "intermediate",
    recommended_duration: 10,
    recommended_reps: 15,
    equipment_required: ["mid iron"],
    clubs: ["7_iron"],
    metric_to_track: "Balanced finishes",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: null,
    regression_level: "drill_three_to_one_tempo",
  },

  // ----------------------------------------------------------------- driver
  {
    id: "drill_driver_fairway_finder",
    name: "Fairway Finder",
    category: "driver",
    sub_category: "accuracy",
    description: "A simulated 30-yard-wide fairway on the range. Fourteen tee shots, one score.",
    instructions: [
      "Pick two range markers roughly 30 yards apart.",
      "Hit fourteen drivers, changing target every shot.",
      "Count a fairway only if you would be in play from that line.",
    ],
    skill_trained: "start_line",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 14,
    equipment_required: ["driver"],
    clubs: ["driver"],
    metric_to_track: "Fairways hit",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: "drill_driver_pressure_ladder",
    regression_level: "drill_tee_height_strike",
  },
  {
    id: "drill_tee_height_strike",
    name: "Tee Height Strike Window",
    category: "driver",
    sub_category: "contact",
    description: "Strike location on the driver face, measured with face spray.",
    instructions: [
      "Spray the driver face.",
      "Hit ten drives and record where each strike landed on the face.",
      "Target a strike that is centre to slightly high and toward the toe.",
    ],
    skill_trained: "centered_contact",
    difficulty: "beginner",
    recommended_duration: 12,
    recommended_reps: 10,
    equipment_required: ["driver", "face spray"],
    clubs: ["driver"],
    metric_to_track: "Strikes in the window",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: "drill_driver_fairway_finder",
    regression_level: null,
  },
  {
    id: "drill_driver_pressure_ladder",
    name: "Driver Pressure Ladder",
    category: "pressure_practice",
    sub_category: "driver",
    description: "Consecutive fairways required. One miss resets the ladder.",
    instructions: [
      "Define a fairway width and commit to it.",
      "Hit until you string five consecutive fairways.",
      "A miss resets the count to zero. Record how many attempts it took.",
    ],
    skill_trained: "pressure_performance",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 20,
    equipment_required: ["driver"],
    clubs: ["driver"],
    metric_to_track: "Longest fairway streak",
    metric_unit: "streak",
    scoring_method: "streak",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_driver_fairway_finder",
  },

  // ------------------------------------------------------------------ woods
  {
    id: "drill_fairway_wood_sweep",
    name: "Fairway Wood Sweep",
    category: "woods",
    sub_category: "contact",
    description: "Turf-first contact with a 3 wood off the deck, the shot most amateurs never practise.",
    instructions: [
      "Place a tee one inch in front of the ball.",
      "Hit fifteen 3 woods off the turf, clipping the tee after the ball.",
      "Any fat contact is a failed rep.",
    ],
    skill_trained: "strike_quality",
    difficulty: "advanced",
    recommended_duration: 12,
    recommended_reps: 15,
    equipment_required: ["3 wood", "tees"],
    clubs: ["3_wood", "5_wood"],
    metric_to_track: "Clean sweeps",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_hybrid_confidence",
  },
  {
    id: "drill_hybrid_confidence",
    name: "Hybrid Launch Window",
    category: "woods",
    sub_category: "long game",
    description: "Hybrids from a variety of lies, judged on launch window rather than distance.",
    instructions: [
      "Alternate between a clean lie and a light rough lie.",
      "Hit fifteen shots, judging each on whether it launched inside your normal window.",
      "Record any that ballooned or came out low and left.",
    ],
    skill_trained: "trajectory_control",
    difficulty: "intermediate",
    recommended_duration: 12,
    recommended_reps: 15,
    equipment_required: ["hybrid"],
    clubs: ["3_hybrid", "4_hybrid"],
    metric_to_track: "Shots in the launch window",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_fairway_wood_sweep",
    regression_level: null,
  },

  // ------------------------------------------------------------- long irons
  {
    id: "drill_long_iron_ladder",
    name: "Long Iron Distance Ladder",
    category: "long_irons",
    sub_category: "distance control",
    description: "Three long-iron carries at increasing distance without losing strike quality.",
    instructions: [
      "Hit five 5 irons at 80% effort and note the carry spread.",
      "Repeat with a 4 iron, then a 3 iron or hybrid.",
      "Count a rep as good if the carry is within 8 yards of your stock number.",
    ],
    skill_trained: "distance_control",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["long irons"],
    clubs: ["3_iron", "4_iron", "5_iron"],
    metric_to_track: "Carries inside 8 yards",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_9_ball_contact",
  },

  // -------------------------------------------------------------- mid irons
  {
    id: "drill_150_distance_control",
    name: "150-Yard Distance Control",
    category: "distance_control",
    sub_category: "mid irons",
    description:
      "Twelve shots at a single 150-yard target, scored on how many finish inside a 15-yard circle.",
    instructions: [
      "Pick a target at your stock 150 yard number.",
      "Hit twelve shots with the same club and the same routine.",
      "Count a shot as good if it finishes inside a 15-yard circle around the target.",
    ],
    skill_trained: "distance_control",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 12,
    equipment_required: ["mid iron", "range with yardage markers"],
    clubs: ["7_iron", "8_iron"],
    metric_to_track: "Shots inside the circle",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.67,
    progression_level: "drill_random_approach_challenge",
    regression_level: "drill_9_ball_contact",
  },
  {
    id: "drill_three_quarter_ladder",
    name: "Three-Quarter Swing Ladder",
    category: "mid_irons",
    sub_category: "distance control",
    description: "Full, three-quarter and half swings with one club to build in-between yardages.",
    instructions: [
      "With an 8 iron, hit five full, five three-quarter and five half swings.",
      "Record the carry of each group.",
      "A rep is good if it lands within 5 yards of that group average.",
    ],
    skill_trained: "distance_control",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["mid iron"],
    clubs: ["8_iron", "9_iron"],
    metric_to_track: "Shots inside 5 yards of group average",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_random_approach_challenge",
    regression_level: null,
  },

  // ------------------------------------------------------------ short irons
  {
    id: "drill_short_iron_dartboard",
    name: "Short Iron Dartboard",
    category: "short_irons",
    sub_category: "approach",
    description: "Scoring-club accuracy inside 130 yards, scored like darts.",
    instructions: [
      "Pick a flag at roughly 120 yards.",
      "Hit fifteen shots, scoring 3 for inside 10 yards, 1 for inside 20, 0 otherwise.",
      "Record total points out of a possible 45.",
    ],
    skill_trained: "distance_control",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["short irons"],
    clubs: ["9_iron", "pw"],
    metric_to_track: "Points scored",
    metric_unit: "pts",
    scoring_method: "percentage",
    success_threshold: 0.6,
    progression_level: "drill_random_approach_challenge",
    regression_level: null,
  },

  // ---------------------------------------------------------------- wedges
  {
    id: "drill_wedge_matrix",
    name: "Wedge Distance Matrix",
    category: "wedges",
    sub_category: "distance control",
    description:
      "Three wedges by three swing lengths gives nine repeatable yardages. The foundation of wedge play.",
    instructions: [
      "For each wedge, hit five shots at 9 o'clock, 10 o'clock and full.",
      "Record the average carry for each combination.",
      "Score a rep good if the carry is within 4 yards of that combination average.",
    ],
    skill_trained: "distance_control",
    difficulty: "intermediate",
    recommended_duration: 20,
    recommended_reps: 45,
    equipment_required: ["wedges", "launch feedback or yardage markers"],
    clubs: ["gw", "sw", "lw"],
    metric_to_track: "Carries inside 4 yards",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_wedge_random_yardage",
    regression_level: "drill_strike_zone_wedge",
  },
  {
    id: "drill_wedge_random_yardage",
    name: "Random Wedge Yardage Call",
    category: "random_practice",
    sub_category: "wedges",
    description: "A partner or a random number generator calls the yardage. No two shots alike.",
    instructions: [
      "Generate a random yardage between 40 and 110.",
      "Play a full pre-shot routine before every shot.",
      "Score inside 8% of the called distance as a success.",
    ],
    skill_trained: "distance_control",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["wedges"],
    clubs: ["gw", "sw", "lw", "pw"],
    metric_to_track: "Shots inside 8% of target",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.55,
    progression_level: null,
    regression_level: "drill_wedge_matrix",
  },

  // --------------------------------------------------------------- pitching
  {
    id: "drill_pitch_trajectory",
    name: "Three-Trajectory Pitch",
    category: "pitching",
    sub_category: "trajectory",
    description: "Low, medium and high pitches to the same target from 30 yards.",
    instructions: [
      "From 30 yards, hit five low, five medium and five high pitches.",
      "All fifteen must finish within 15 feet.",
      "Vary ball position and face loft rather than swinging harder.",
    ],
    skill_trained: "trajectory_control",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["wedges", "short game area"],
    clubs: ["sw", "lw"],
    metric_to_track: "Pitches inside 15 feet",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_pitch_landing_zone",
  },
  {
    id: "drill_pitch_landing_zone",
    name: "Landing Zone Pitching",
    category: "pitching",
    sub_category: "control",
    description: "A towel as a landing zone teaches you to control carry, not total distance.",
    instructions: [
      "Place a towel at your intended landing spot.",
      "Hit twenty pitches from 20 to 40 yards.",
      "A rep counts only if the ball first bounces on the towel.",
    ],
    skill_trained: "pitching_proximity",
    difficulty: "intermediate",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["towel", "wedges"],
    clubs: ["sw", "gw"],
    metric_to_track: "Landings on the towel",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.55,
    progression_level: "drill_pitch_trajectory",
    regression_level: null,
  },

  // --------------------------------------------------------------- chipping
  {
    id: "drill_chip_circle",
    name: "Three-Foot Chip Circle",
    category: "chipping",
    sub_category: "proximity",
    description: "Twenty chips, scored on how many finish inside a three-foot circle.",
    instructions: [
      "Set a three-foot circle around the hole with tees.",
      "Chip twenty balls from four different lies.",
      "Record how many finish inside the circle.",
    ],
    skill_trained: "chipping_proximity",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 20,
    equipment_required: ["tees", "wedges", "short game area"],
    clubs: ["pw", "gw", "sw"],
    metric_to_track: "Chips inside 3 feet",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.5,
    progression_level: "drill_up_and_down_game",
    regression_level: "drill_one_club_chipping",
  },
  {
    id: "drill_one_club_chipping",
    name: "One-Club Chipping",
    category: "chipping",
    sub_category: "technique",
    description: "Every chip with the same club, varying only ball position and length of stroke.",
    instructions: [
      "Use a pitching wedge for every shot.",
      "Chip to three different flags without changing club.",
      "Score a rep good if the ball finishes within six feet.",
    ],
    skill_trained: "chipping_proximity",
    difficulty: "beginner",
    recommended_duration: 12,
    recommended_reps: 24,
    equipment_required: ["pitching wedge"],
    clubs: ["pw"],
    metric_to_track: "Chips inside 6 feet",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: "drill_chip_circle",
    regression_level: null,
  },
  {
    id: "drill_up_and_down_game",
    name: "Nine-Point Up and Down",
    category: "course_simulation",
    sub_category: "short game",
    description: "Nine different short-game situations, each played out to the hole.",
    instructions: [
      "Play nine shots: three chips, three pitches, three bunker shots.",
      "Hole out every one with the putter.",
      "Score an up and down as a success.",
    ],
    skill_trained: "chipping_proximity",
    difficulty: "advanced",
    recommended_duration: 25,
    recommended_reps: 9,
    equipment_required: ["short game area", "wedges", "putter"],
    clubs: ["pw", "gw", "sw", "lw", "putter"],
    metric_to_track: "Up and downs",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.45,
    progression_level: null,
    regression_level: "drill_chip_circle",
  },

  // ----------------------------------------------------------------- bunker
  {
    id: "drill_bunker_line",
    name: "Bunker Entry Line",
    category: "bunker",
    sub_category: "technique",
    description: "A line drawn in the sand shows exactly where the club is entering.",
    instructions: [
      "Draw a line in the sand and set up with the ball one inch ahead of it.",
      "Make twenty swings entering the sand on the line.",
      "Any entry behind the line is a failed rep.",
    ],
    skill_trained: "bunker_technique",
    difficulty: "beginner",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["practice bunker", "sand wedge"],
    clubs: ["sw"],
    metric_to_track: "Entries on the line",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.7,
    progression_level: "drill_bunker_distance",
    regression_level: null,
  },
  {
    id: "drill_bunker_distance",
    name: "Bunker Distance Control",
    category: "bunker",
    sub_category: "distance control",
    description: "Three different bunker distances, same technique, different swing length.",
    instructions: [
      "Set targets at 10, 20 and 30 feet onto the green.",
      "Hit five to each, changing only the length of the swing.",
      "Count a rep as good if the ball finishes within six feet.",
    ],
    skill_trained: "bunker_technique",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["practice bunker", "sand wedge"],
    clubs: ["sw", "lw"],
    metric_to_track: "Bunker shots inside 6 feet",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.5,
    progression_level: null,
    regression_level: "drill_bunker_line",
  },

  // ---------------------------------------------------------------- putting
  {
    id: "drill_gate_putting",
    name: "Putting Gate",
    category: "putting",
    sub_category: "face control",
    description: "Two tees barely wider than the putter head test start line from three feet.",
    instructions: [
      "Set two tees just wider than the putter head, six inches ahead of the ball.",
      "Hit thirty putts from three feet through the gate.",
      "Any tee contact is a failed rep.",
    ],
    skill_trained: "short_putt_conversion",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 30,
    equipment_required: ["2 tees", "putter"],
    clubs: ["putter"],
    metric_to_track: "Putts through the gate and holed",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.85,
    progression_level: "drill_clock_putting",
    regression_level: null,
  },
  {
    id: "drill_clock_putting",
    name: "Clock Drill",
    category: "putting",
    sub_category: "short putts",
    description: "Six balls in a circle at four feet. Miss one and start again.",
    instructions: [
      "Place six balls in a circle four feet from the hole.",
      "Hole all six in a row.",
      "A miss restarts the circle. Record how many attempts it took.",
    ],
    skill_trained: "short_putt_conversion",
    difficulty: "intermediate",
    recommended_duration: 12,
    recommended_reps: 24,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Four-foot conversion",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.85,
    progression_level: "drill_pressure_putting_ladder",
    regression_level: "drill_gate_putting",
  },
  {
    id: "drill_lag_ladder",
    name: "Lag Putting Ladder",
    category: "putting",
    sub_category: "speed",
    description: "Long putts scored on whether they finish inside a three-foot circle.",
    instructions: [
      "Putt from 30, 40 and 50 feet, five balls each.",
      "Score a success when the ball finishes inside three feet.",
      "Never look at the line, only at the speed.",
    ],
    skill_trained: "lag_putting",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Lag putts inside 3 feet",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: "drill_three_putt_avoidance",
    regression_level: null,
  },
  {
    id: "drill_speed_control_uphill",
    name: "Uphill and Downhill Speed",
    category: "putting",
    sub_category: "speed",
    description: "The same twenty-foot putt uphill and downhill, matching finish distance.",
    instructions: [
      "Find a twenty-foot putt with obvious slope.",
      "Hit five uphill and five downhill.",
      "A rep succeeds if the ball finishes between the hole and eighteen inches past.",
    ],
    skill_trained: "speed_control",
    difficulty: "advanced",
    recommended_duration: 12,
    recommended_reps: 10,
    equipment_required: ["putter", "sloped green"],
    clubs: ["putter"],
    metric_to_track: "Putts finishing in the zone",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.55,
    progression_level: null,
    regression_level: "drill_lag_ladder",
  },
  {
    id: "drill_three_putt_avoidance",
    name: "Three-Putt Avoidance Game",
    category: "putting",
    sub_category: "scoring",
    description: "Eighteen long putts played out to the hole. Count the three putts.",
    instructions: [
      "Play eighteen putts from between 25 and 60 feet.",
      "Hole out every one.",
      "Record how many took three or more strokes.",
    ],
    skill_trained: "lag_putting",
    difficulty: "intermediate",
    recommended_duration: 20,
    recommended_reps: 18,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Two putts or better",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.85,
    progression_level: null,
    regression_level: "drill_lag_ladder",
  },
  {
    id: "drill_green_reading_ladder",
    name: "Read and Commit",
    category: "putting",
    sub_category: "green reading",
    description: "Call the break before every putt, then score the read rather than the result.",
    instructions: [
      "Before each putt, state the break in cups out loud.",
      "Hit fifteen putts from 12 to 25 feet.",
      "Score the read correct if the ball took the called amount of break.",
    ],
    skill_trained: "green_reading",
    difficulty: "intermediate",
    recommended_duration: 15,
    recommended_reps: 15,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Correct reads",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: null,
  },

  // --------------------------------------------------------- random/pressure
  {
    id: "drill_random_approach_challenge",
    name: "Random Approach Challenge",
    category: "random_practice",
    sub_category: "approach",
    description:
      "Every shot a different club, a different target and a full routine. The transfer test for range work.",
    instructions: [
      "Write twelve yardages between 110 and 190 on a card and shuffle them.",
      "Play each one as if it were on the course, with a full routine.",
      "Score a shot as a success if it finishes inside your proximity target for that range.",
    ],
    skill_trained: "distance_control",
    difficulty: "advanced",
    recommended_duration: 20,
    recommended_reps: 12,
    equipment_required: ["full bag", "range"],
    clubs: ["5_iron", "6_iron", "7_iron", "8_iron", "9_iron", "pw"],
    metric_to_track: "Shots inside proximity target",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.55,
    progression_level: "drill_par18_simulation",
    regression_level: "drill_150_distance_control",
  },
  {
    id: "drill_one_ball_pressure",
    name: "One-Ball Pressure Test",
    category: "pressure_practice",
    sub_category: "transfer",
    description: "One ball, one attempt, a real consequence. The closest a range gets to the first tee.",
    instructions: [
      "Pick ten shots you will face on your next round.",
      "Play each once, with a full routine and no rehearsal.",
      "Set a consequence for failure before you start.",
    ],
    skill_trained: "pressure_performance",
    difficulty: "advanced",
    recommended_duration: 20,
    recommended_reps: 10,
    equipment_required: ["full bag"],
    clubs: ["driver", "7_iron", "sw", "putter"],
    metric_to_track: "Shots executed as planned",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.6,
    progression_level: null,
    regression_level: "drill_random_approach_challenge",
  },
  {
    id: "drill_pressure_putting_ladder",
    name: "Pressure Putting Ladder",
    category: "pressure_practice",
    sub_category: "putting",
    description: "Three to eight feet, one ball at each distance. A miss sends you back to three.",
    instructions: [
      "Place balls at 3, 4, 5, 6, 7 and 8 feet.",
      "Hole them in order without a miss.",
      "A miss restarts at three feet. Record the best ladder reached.",
    ],
    skill_trained: "pressure_performance",
    difficulty: "advanced",
    recommended_duration: 15,
    recommended_reps: 18,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Highest rung reached",
    metric_unit: "rung",
    scoring_method: "streak",
    success_threshold: 0.66,
    progression_level: null,
    regression_level: "drill_clock_putting",
  },

  // ------------------------------------------------------- course simulation
  {
    id: "drill_par18_simulation",
    name: "Par 18 Short Game Course",
    category: "course_simulation",
    sub_category: "scoring",
    description: "Nine short-game holes with a par of two each. Play a real score.",
    instructions: [
      "Choose nine short-game shots from varied lies, none longer than 40 yards.",
      "Play each to the hole with the putter finishing out.",
      "Par is two per hole. Record your score against 18.",
    ],
    skill_trained: "course_management",
    difficulty: "advanced",
    recommended_duration: 30,
    recommended_reps: 9,
    equipment_required: ["short game area", "wedges", "putter"],
    clubs: ["pw", "gw", "sw", "lw", "putter"],
    metric_to_track: "Score against par 18",
    metric_unit: "strokes",
    scoring_method: "percentage",
    success_threshold: 0.55,
    progression_level: null,
    regression_level: "drill_up_and_down_game",
  },
  {
    id: "drill_range_nine_holes",
    name: "Nine Holes on the Range",
    category: "course_simulation",
    sub_category: "transfer",
    description: "Play your home course in your head, hitting every shot on the range.",
    instructions: [
      "Play the first nine of your home course shot by shot.",
      "Change club and target on every shot, with a full routine.",
      "Score a shot as a success if it would have been playable.",
    ],
    skill_trained: "course_management",
    difficulty: "intermediate",
    recommended_duration: 30,
    recommended_reps: 18,
    equipment_required: ["full bag", "range"],
    clubs: ["driver", "3_wood", "5_iron", "7_iron", "9_iron", "sw"],
    metric_to_track: "Playable shots",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.65,
    progression_level: "drill_one_ball_pressure",
    regression_level: null,
  },

  // --------------------------------------------------------------- warm ups
  {
    id: "drill_warmup_ladder",
    name: "Warm-Up Ladder",
    category: "full_swing",
    sub_category: "warm up",
    description: "Wedge to driver in eight minutes, building speed gradually.",
    instructions: [
      "Five half wedges, five three-quarter 9 irons, five 7 irons, three hybrids, three drivers.",
      "Never swing above 80% until the mid irons.",
      "Finish with two shots to the target you will start the session on.",
    ],
    skill_trained: "tempo",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 21,
    equipment_required: ["full bag"],
    clubs: ["pw", "9_iron", "7_iron", "4_hybrid", "driver"],
    metric_to_track: "Reps completed",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.9,
    progression_level: null,
    regression_level: null,
  },
  {
    id: "drill_putting_warmup",
    name: "Putting Warm-Up Circuit",
    category: "putting",
    sub_category: "warm up",
    description: "Speed first, then line, in six minutes.",
    instructions: [
      "Six long putts looking only at the hole.",
      "Six three-footers with a gate.",
      "Three putts from your average first-putt distance.",
    ],
    skill_trained: "speed_control",
    difficulty: "beginner",
    recommended_duration: 8,
    recommended_reps: 15,
    equipment_required: ["putter", "putting green"],
    clubs: ["putter"],
    metric_to_track: "Circuit completed",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.9,
    progression_level: null,
    regression_level: null,
  },

  // ----------------------------------------------------------- path control
  {
    id: "drill_headcover_path",
    name: "Headcover Path Gate",
    category: "club_path",
    sub_category: "full swing",
    description: "A headcover outside the ball forces an in-to-out delivery.",
    instructions: [
      "Place a headcover a foot outside and slightly ahead of the ball.",
      "Hit twenty 7 irons without hitting the headcover.",
      "Move it closer as the pattern improves.",
    ],
    skill_trained: "club_path",
    difficulty: "intermediate",
    recommended_duration: 12,
    recommended_reps: 20,
    equipment_required: ["headcover"],
    clubs: ["7_iron", "6_iron"],
    metric_to_track: "Shots missing the headcover",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.75,
    progression_level: "drill_shape_window",
    regression_level: "drill_split_hand_face",
  },
  {
    id: "drill_toe_up_path",
    name: "Toe-Up Checkpoint",
    category: "club_path",
    sub_category: "takeaway",
    description: "A takeaway checkpoint that sets the path before the swing gets long.",
    instructions: [
      "Swing to hip height and stop with the shaft parallel to the ground.",
      "Check the toe points straight up and the shaft points at the target line.",
      "Twenty rehearsals, then ten balls holding the same checkpoint.",
    ],
    skill_trained: "club_path",
    difficulty: "beginner",
    recommended_duration: 10,
    recommended_reps: 30,
    equipment_required: ["mirror or phone"],
    clubs: ["7_iron"],
    metric_to_track: "Checkpoints correct",
    metric_unit: "%",
    scoring_method: "ratio",
    success_threshold: 0.8,
    progression_level: "drill_headcover_path",
    regression_level: null,
  },
];

export const DRILLS_BY_ID = new Map(DRILLS.map((d) => [d.id, d]));

export function getDrill(id: string): Drill | undefined {
  return DRILLS_BY_ID.get(id);
}
