/**
 * Emits the Supabase seed SQL from the same TypeScript seed data the app uses
 * in demo mode, so the two can never drift.
 *
 *   npm run seed:sql
 *
 * Writes:
 *   supabase/seed/seed.sql         reference data (drills, reference swings)
 *   supabase/seed/demo-player.sql  the demo player, for an existing auth user
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { DRILLS } from "../lib/seed/drills";
import { REFERENCE_SWINGS } from "../lib/seed/reference-swings";
import { demoData } from "../lib/seed/demo-player";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "supabase", "seed");

type Value = string | number | boolean | null | undefined | unknown[] | object;

function lit(value: Value): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value)) {
    if (value.length === 0) return "'{}'";
    // An array of objects is a jsonb column (hole specs, plan targets);
    // an array of strings is a text[] column.
    if (typeof value[0] === "object") return `${quote(JSON.stringify(value))}::jsonb`;
    return `array[${value.map((v) => quote(String(v))).join(", ")}]::text[]`;
  }
  if (typeof value === "object") return `${quote(JSON.stringify(value))}::jsonb`;
  return quote(value);
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, Value>[], conflictKey = "id"): string {
  if (rows.length === 0) return "";
  const columns = Object.keys(rows[0]!);
  const values = rows
    .map((row) => `  (${columns.map((c) => lit(row[c])).join(", ")})`)
    .join(",\n");
  const updates = columns
    .filter((c) => c !== conflictKey)
    .map((c) => `${c} = excluded.${c}`)
    .join(", ");
  return [
    `insert into public.${table} (${columns.join(", ")}) values`,
    values,
    `on conflict (${conflictKey}) do update set ${updates};`,
    "",
  ].join("\n");
}

// -------------------------------------------------------- reference data

const referenceSql = [
  "-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.",
  "-- Reference data shared by every user.",
  "",
  insert(
    "drills",
    DRILLS.map((d) => ({
      id: d.id,
      name: d.name,
      category: d.category,
      sub_category: d.sub_category,
      description: d.description,
      instructions: d.instructions,
      skill_trained: d.skill_trained,
      difficulty: d.difficulty,
      recommended_duration: d.recommended_duration,
      recommended_reps: d.recommended_reps,
      equipment_required: d.equipment_required,
      clubs: d.clubs,
      metric_to_track: d.metric_to_track,
      metric_unit: d.metric_unit,
      scoring_method: d.scoring_method,
      success_threshold: d.success_threshold,
      progression_level: d.progression_level,
      regression_level: d.regression_level,
    })),
  ),
  insert(
    "reference_swings",
    REFERENCE_SWINGS.map((r) => ({
      id: r.id,
      name: r.name,
      year: r.year,
      pattern: r.pattern,
      summary: r.summary,
      useful_similarities: r.useful_similarities,
      potential_differences: r.potential_differences,
      features: r.features,
    })),
  ),
].join("\n");

// ----------------------------------------------------------- demo player

const demo = demoData();
const USER = ":'demo_user_id'";

const demoSql = [
  "-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.",
  "--",
  "-- Loads the demo player into an EXISTING Supabase auth user. Create the",
  "-- account first, then run:",
  "--",
  "--   psql <connection-string> -v demo_user_id=<uuid> -f supabase/seed/demo-player.sql",
  "--",
  "-- Every strokes-gained number, weakness and trend is derived from the shots",
  "-- below by the application, not stored here.",
  "",
  "begin;",
  "",
  insert("courses", demo.courses.map((c) => ({
    id: c.id,
    user_id: null,
    name: c.name,
    city: c.city,
    par: c.par,
    holes: c.holes,
    created_at: c.created_at,
  }))),
  insert("player_profiles", [
    {
      id: demo.profile.id,
      user_id: "__USER__",
      display_name: demo.profile.display_name,
      handicap_index: demo.profile.handicap_index,
      experience_level: demo.profile.experience_level,
      dominant_hand: demo.profile.dominant_hand,
      typical_score: demo.profile.typical_score,
      average_driver_distance: demo.profile.average_driver_distance,
      swing_pattern: demo.profile.swing_pattern,
      common_miss: demo.profile.common_miss,
      primary_goal: demo.profile.primary_goal,
      secondary_goals: demo.profile.secondary_goals,
      practice_days_per_week: demo.profile.practice_days_per_week,
      typical_practice_duration: demo.profile.typical_practice_duration,
      facilities: demo.profile.facilities,
      bag: demo.profile.bag,
      created_at: demo.profile.created_at,
      updated_at: demo.profile.updated_at,
    },
  ]),
  insert("handicap_entries", demo.handicapHistory.map((h) => ({ ...h, user_id: "__USER__" }))),
  insert("rounds", demo.rounds.map((r) => ({ ...r, user_id: "__USER__" }))),
  insert("shots", demo.shots.map((s) => ({ ...s, user_id: "__USER__" }))),
  insert(
    "practice_sessions",
    demo.practiceSessions.map((s) => ({ ...s, user_id: "__USER__" })),
  ),
  insert("practice_items", demo.practiceItems),
  insert("drill_attempts", demo.drillAttempts.map((a) => ({ ...a, user_id: "__USER__" }))),
  insert("training_plans", [{ ...demo.plan, user_id: "__USER__" }]),
  insert("plan_sessions", demo.planSessions),
  insert("plan_adaptations", demo.planAdaptations),
  insert("swing_sessions", demo.swingSessions.map((s) => ({ ...s, user_id: "__USER__" }))),
  insert("swing_findings", demo.swingFindings.map((f) => ({ ...f, user_id: "__USER__" }))),
  "commit;",
  "",
]
  .join("\n")
  .replaceAll(`'__USER__'`, `${USER}::uuid`);

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "seed.sql"), referenceSql, "utf8");
writeFileSync(join(outDir, "demo-player.sql"), demoSql, "utf8");

console.log(
  `Wrote supabase/seed/seed.sql (${DRILLS.length} drills, ${REFERENCE_SWINGS.length} reference swings)`,
);
console.log(
  `Wrote supabase/seed/demo-player.sql (${demo.rounds.length} rounds, ${demo.shots.length} shots, ${demo.practiceSessions.length} practice sessions)`,
);
